language: java
jdk:
- oraclejdk11
- openjdk11
sudo: false
notifications:
  email: false
  slack:
    secure: Rxc4U+/hZ7RrihPdMGHCCuWHEmzW9SMyix5XgL0jrnKRE4LHs2lBWM05SCPfiLhw3p7+qOIwUc/XoKDcKTEKPhxinDotznN8w4vPEtf0Uzi8asRS30uRgbq48hTS3/M9ljFnt4YOj5RvU+/10FT3+MbOPi/hvpGWV57Uu3R05Vd8W9bsrLU9b7uxdAKzIr+6kp8sc49V50Y3FvULqHwkWv8817uyzCUew/N1ycQi8OqGSfwy9NRIpf5yybgJeCQOlc54neRc2MxNOG4BL8Q4HJq9+P1c86WcsYQhxINmU8l5B0F4zLKpr54iI9iifOsO/KyAEcH33y1QMMcRN/4EOC9xMuZzmZO0zlfu6nK6QoPGjlaZI2k1RMDWdJTLIClbpD13WdHXjI3q9CzzTpIBqKOP8AOwbhJ+PI1aCaxgtFssjUcBxCZRXrImlPeL//oHjGIrejnr1kPRuTGFrPhBgtHQ6f4k3EuMAK+w3c87XqxT2uI8QdvQahwJXIo8gwHZWfENT2ssPz98G7mIoMmtFjNSP8qIzdAF7Ehe1DgkE95++usa3SRHcx0n371FDQW06PNDgb/BYFO8fJMnbgi9ctDSztWNLR2Uv94qDcoEzQaEENOOYlYE3QtTs9zOEnmNg0FJrKelJChO3/G4RbyIOeIl5eqDZBX3qKfYuNHu1h4=
after_success:
- mvn clean test jacoco:report coveralls:report
deploy:
  provider: script
  script: mvn deploy --settings travis-settings.xml -DskipTests=true -B
  on:
    jdk: oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
