language: java
jdk:
- oraclejdk11
- openjdk11
sudo: false
notifications:
  email: false
  slack:
    secure: 2bhFKY2fIyYTfH6oEayL4nHsjeWDRnknHnUYtFlKixIgwmqm62/zElTaE1skpeOdPI6/ZcYPatZlddPTo+UpxjgkGr7VoaQjMuu9RD8kIN6bLjuwd/fjvhjJO5YLuTRTR3DBcFpkKTb4OzZlseKhrrkhJbISMWBysXiFMamfQVmluKXSyM7qNo6L7NgxkJjAewL9xLyG+bbfUtUj900/gjugC5aArQHSEYFbfY1BzgZcqRdRkrQl7bAoTiOT77i2z+0pnnEh2f2Bm1HEV2kG2eXvdWs8lzgWx+3DWZbhtGqbi0fJG+FXaZxjkqyaF89EF5617bQKT2HaZndzjBlNcVvfdMx8sqYATTp83GbhHE1d0IpB8V+T90Tn0S5dJQD/qbu/ROMirYTCDijS/Mja9b+y0VQeVE1hn7nV+qivfA5gy8wTbcbR4VEbWDOGVcII+miN5askR3ggrJPOLzD9DnTIOlBFMdP3wu1N7JNx4deXVUZAuHRN/3EV1DsTQaeFEmrzs63c0rvwwRQ+nldBMxPDFqrs2x5MGbolj22snH/DHz6QtEsZGkPLnNJzrOy43i/sRUN0t9+3tpRlam6KwOP7j7OfL+FCyIv5E1BhHpZhrOkpCzRmC5umU0Q06XmMNq8CIWC181yKwcXE/s8KO751Qu434O73aBpt90Dzr+8=
after_success:
- mvn clean test jacoco:report coveralls:report
deploy:
  provider: script
  script: mvn deploy --settings travis-settings.xml -DskipTests=true -B
  on:
    jdk: oraclejdk11
cache:
  directories:
  - "$HOME/.m2"
